#mysql & phpmyadmin exposed docker-compose
version: '3.3'

services:
  db1:
    image: mysql:5.7
    restart: always
    ports:
      - 3301:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql1:/var/lib/mysql
  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db1
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db1
######################################
  db2:
    image: mysql:5.7
    restart: always
    ports:
      - 3302:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql2:/var/lib/mysql
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db2
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db2
######################################
  db3:
    image: mysql:5.7
    restart: always
    ports:
      - 3303:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql3:/var/lib/mysql
  phpmyadmin3:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: db3
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db3
######################################
  db4:
    image: mysql:5.7
    restart: always
    ports:
      - 3304:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql4:/var/lib/mysql
  phpmyadmin4:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8084:80
    environment:
      PMA_HOST: db4
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db4
######################################
  db5:
    image: mysql:5.7
    restart: always
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql5:/var/lib/mysql
  phpmyadmin5:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: db5
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db5
######################################
  db6:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql6:/var/lib/mysql
  phpmyadmin6:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8086:80
    environment:
      PMA_HOST: db6
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db6
######################################
  db7:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql7:/var/lib/mysql
  phpmyadmin7:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8087:80
    environment:
      PMA_HOST: db7
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db7
######################################
  db8:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql8:/var/lib/mysql
  phpmyadmin8:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: db8
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db8
######################################
  db9:
    image: mysql:5.7
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql9:/var/lib/mysql
  phpmyadmin9:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
      PMA_HOST: db9
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db9
######################################